# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy takelruby arm64 image to dockerhub'
  task arm64: %w[rubylint
                 images:project:molecule:lint
                 images:project:update
                 images:project:build
                 images:project:molecule:test
                 dockerhub:project:tag:latest:arm64
                 dockerhub:project:push:latest:arm64
                 dockerhub:project:tag:version:arm64
                 dockerhub:project:push:version:arm64
                 dockerhub:project:pull:latest:amd64
                 dockerhub:project:pull:version:amd64
                 dockerhub:project:manifest:create:latest
                 dockerhub:project:manifest:push:latest
                 dockerhub:project:manifest:create:version
                 dockerhub:project:manifest:push:version]
end
