# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy takelruby image to dockerhub'
  task prod: %w[dockerhub:login
                rubylint
                images:project:molecule:lint
                images:project:build
                images:project:molecule:test
                dockerhub:project:tag
                dockerhub:project:push]
end
