---
name: takelruby
version: 3.2

images:
  project:
    base_user: takelwerk
    base_repo: takelslim
    base_tag: latest
    layers:
      - site
    target_user: takelwerk
    target_repo: takelruby

local_user: packer_local
