---
name: takelruby
version: 3.0

pipelines:
  - prod

images:
  project:
    base_user: takelage
    base_repo: takelslim
    base_tag: latest
    layers:
      - site
    omit_pipeline_name: prod
    target_user: takelwerk
    target_repo: takelruby
  ruby26:
    base_user: takelage
    base_repo: takelslim
    base_tag: latest
    layers:
      - site
    omit_pipeline_name: prod
    target_user: takelwerk
    target_repo: takelruby
    target_tag: 2.6

local_user: packer_local
