---
name: takelruby
version: 3.0

images:
  project:
    base_user: takelwerk
    base_repo: takelslim
    base_tag: latest
    layers:
      - site
    target_user: takelwerk
    target_repo: takelruby
  ruby26:
    base_user: takelwerk
    base_repo: takelslim
    base_tag: latest
    layers:
      - site
    target_user: takelwerk
    target_repo: takelruby
    target_tag: 2.6

local_user: packer_local
